name: GitHub Actions test
on: [push]
jobs:
  runs-on: windows-latest
  steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: x64

    - name: pip
      run: pip install yara-python pyinstaller

    - name: build
      run: pyinstaller --onefile main.py

    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: pe
        path: dist/main.exe
